/*
 *  This file is part of the X10 project (http://x10-lang.org).
 *
 *  This file is licensed to You under the Eclipse Public License (EPL);
 *  You may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *      http://www.opensource.org/licenses/eclipse-1.0.php
 *
 *  (C) Copyright IBM Corporation 2006-2014.
 */

import harness.x10Test;

// MANAGED_X10_ONLY

public class JavaException4 extends x10Test {

	public def constrainedType(): Boolean {
		val out = Console.OUT;
		var passed:Boolean = false;
		try {
			out.println("in try");
			throw new java.lang.Exception();
		} catch (e:java.lang.IndexOutOfBoundsException) {
			out.println("in catch java.lang.IndexOutOfBoundsException");
		} catch (e:java.lang.RuntimeException) {
			out.println("in catch java.lang.RuntimeException");
		} catch (e:x10.lang.Exception{self != null}) {
			out.println("in catch x10.lang.Exception");
		} catch (e:java.lang.Throwable) {
			out.println("in catch java.lang.Throwable");
			passed = true;
		} catch (e:x10.lang.Throwable) {
			out.println("in catch x10.lang.Throwable");
		}
		return passed;
	}

    public def plainType(): Boolean {
    	val out = Console.OUT;
    	var passed:Boolean = false;
        try {
        	out.println("in try");
        	throw new java.lang.Exception();
        } catch (e:java.lang.IndexOutOfBoundsException) {
        	out.println("in catch java.lang.IndexOutOfBoundsException");
        } catch (e:java.lang.RuntimeException) {
        	out.println("in catch java.lang.RuntimeException");
        } catch (e:x10.lang.Exception) {
        	out.println("in catch x10.lang.Exception");
        } catch (e:java.lang.Throwable) {
        	out.println("in catch java.lang.Throwable");
        	passed = true;
        } catch (e:x10.lang.Throwable) {
        	out.println("in catch x10.lang.Throwable");
        }
        return passed;
    }

    public def run(): Boolean {
    	chk(plainType());
    	chk(constrainedType());
    	return true;
    }

    public static def main(args: Array[String](1)) {
        new JavaException4().execute();
    }
}
